category_label = [
    'BENIGN', 'PORTSCAN', 'RECONNAISSANCE', 'WEB_ATTACK_BRUTE_FORCE', 'WEB_ATTACK_XSS', 'WEB_ATTACK_SQL_INJECTION',
    'HEARTBLEED', 'EXPLOITS', 'FUZZERS', 'FTP_PATATOR', 'SSH_PATATOR', 'BACKDOOR', 'BOT', 'SHELLCODE', 'WORMS',
    'INFILTRATION', 'DOS_SLOWHTTPTEST', 'DDOS', 'DOS', 'DOS_GOLDENEYE', 'DOS_HULK', 'DOS_SLOWLORIS', 'GENERIC',
    'ANALYSIS'
]
